# Data Preprocessing

## note: accidentally lost come of the code blocks so this notebook doesnt work anymore, might fix later and do feature engineering to improve model performance

In [ ]:
import numpy as np
import pandas as pd

DATA_LOC_TRAIN = '../data/raw/train.csv'
DATA_LOC_TEST = '../data/raw/test.csv'

In [ ]:
dataset_train = pd.read_csv(DATA_LOC_TRAIN)
dataset_test = pd.read_csv(DATA_LOC_TEST)

In [ ]:
dataset_train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
dataset_test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

## Handling missing values

In [153]:
dataset_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [154]:
dataset_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

## Dropping unnecessary columns and handling missing data

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_train['Sex'] = le.fit_transform(df_train['Sex'])

## Exporting data

In [158]:
import os

df_train.to_csv('../data/processed/training_data.csv',index = False)
df_test.to_csv('../data/processed/test_data.csv', index = False)
y_train.to_csv('../data/processed/training_y.csv', index = False)

In [159]:
print(len(df_train))
print(len(y_train))
print(len(df_test))

891
891
418